project:
  type: website
  output-dir: docs
website:
  title: "Lisan Project"
  page-navigation: true
  navbar:
    background: "#003366"
    left:
      - text: "<i class='bi bi-house-door'></i> Home"
        href: index.qmd
      - text: "Course Material"
        href: course-material.qmd
    right:
      - icon: github
        href: https://github.com/LisanProject/Sharh-Waraqat
        aria-label: GitHub

  sidebar:
    style: floating
    collapse-level: 2
    contents:
      - section: "Overview"
        contents:
          - index.qmd
          - course-material.qmd
      
      - section: "Lectures"
        contents:
          - Lectures/01-Introduction-usul-al-fiqh.qmd
          - Lectures/02-Ahkam.qmd

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: true
    toc-location: right
    toc-depth: 3
    toc-expand: 2
    smooth-scroll: true
    number-sections: true
    code-copy: true
    code-overflow: wrap
code-overflow: wrap
